### ISSUE TITLE
Implement whitelist for "not ignored" servers

### ISSUE THREAD

**Issue by LoneDev6** [LoneDev6/BungeePackFix#27]
https://github.com/LoneDev6/BungeePackFix/issues/25

**Comment by LoneDev6** [comment]
What do you think?
```yml
servers:
  enable_lists: true
  invert_check: false
  ignored_servers:
    - ignored_1
    - ignored_2
```

**Comment by LoneDev6** [comment]
Implemented @Coquettishpig

```yml
ignored_servers:
  enabled: true
  invert_check: false
  list:
    - ignored_1
    - ignored_2
```
