### ISSUE TITLE
problem with removing texture

### ISSUE THREAD

**Issue by haroldrc** [LoneDev6/BungeePackFix#31]
I want to make sure that the texture shouldn't be removed in server1 and server2, in all others it should be removed. this is my setup but it doesn't do what i want
```yml
messages:
  ignored_pack:
    enabled: true
    message: "test"
  minimessage_support: false
equal_pack_attributes:
  hash: true
  forced: true
  prompt_message: true
log:
  ignored_respack: false
  sent_respack: false
  debug: false
ignore_hash_in_url: true
main_spigot_server_name: server1
ignored_servers:
  enabled: true
  invert_check: true
  list:
    - server1
    - server2
```
