### ISSUE TITLE
equal_pack_attributes: hash: true | not working for velocity

### ISSUE THREAD

**Issue by ByteExceptionDE** [LoneDev6/BungeePackFix#59]
Velocity 3.3.0-SNAPSHOT (git-59567512-b346)
BungeePackFix_1.1.6-beta1

this is my config:
```
messages:
  minimessage_support: false
  ignored_pack:
    enabled: true
    message: "&6Skipped resourcepack installation (you already loaded it)."
equal_pack_attributes:
  modern_uuid: true
  hash: false
  forced: true
  prompt_message: true
ignore_hash_in_url: true
cancel_modern_resourcepack_remove_packet: true
main_spigot_server_name: "gens-hub"
ignored_servers:
  enabled: false
  invert_check: false
  list:
    - ignored_1
    - ignored_2
log:
  ignored_respack: false
  sent_respack: false
  debug: false
```
main_spigot_server_name is the server that hosts the resource pack and all other subservers have a valid external host configuration like this:

```
    external-host:
      enabled: true
      url: http://**REDACTED IP**:8163/generated.zip#307aaf7e86d249c46eeba6fa67c353c22ac52344
      skip-url-file-type-check___DONT_ASK_HELP_IF_SET_TRUE: false
```

whenever i set **equal_pack_attributes: hash: true** the plugin stops working and the resourcepack will be applied on every server swtich, disabling the option will make it work again.
